services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    MonsieurBiz\SyliusCmsPagePlugin\:
        resource: '../../*'
        exclude: '../../{Component}'

    MonsieurBiz\SyliusCmsPagePlugin\Controller\:
        resource: '../../Controller'
        tags: ['controller.service_arguments']
    
    # Let's try to find the locale from the request path.
    # The priority should be higher than the sylius.context.locale.request_header_based service to avoid 404 errors with 
    MonsieurBiz\SyliusCmsPagePlugin\Context\FindInRequestPathLocaleContext:
        tags:
            - { name: sylius.context.locale, priority: 35 }
    
    MonsieurBiz\SyliusCmsPagePlugin\Context\LastChanceLocaleContext:
        alias: MonsieurBiz\SyliusCmsPagePlugin\Context\FindInRequestPathLocaleContext
        deprecated:
            package: 'monsieurbiz/sylius-cms-page-plugin'
            version: '2.0.3'
            message: 'The "%alias_id%" service alias is deprecated and will be removed in 2.1. Use "MonsieurBiz\SyliusCmsPagePlugin\Context\FindInRequestPathLocaleContext" instead.'

    # Menu item in admin panel
    MonsieurBiz\SyliusCmsPagePlugin\Listener\AdminMenuListener:
        tags:
            - { name: kernel.event_listener, event: sylius.menu.admin.main, method: addAdminMenuItem }

    # Page Forms
    MonsieurBiz\SyliusCmsPagePlugin\Form\Type\PageType:
        arguments:
            $dataClass: '%monsieurbiz_cms_page.model.page.class%'
            $validationGroups: ['monsieurbiz']
    MonsieurBiz\SyliusCmsPagePlugin\Form\Type\PageTranslationType:
        arguments:
            $dataClass: '%monsieurbiz_cms_page.model.page_translation.class%'
            $validationGroups: ['monsieurbiz']

    monsieurbiz.cms_page.datetime_provider:
        class: Symfony\Component\Clock\Clock
        public: true

    # Live components
    sylius_admin.monsieurbiz_cms_page.twig.component.page.form:
        autoconfigure: false
        class: MonsieurBiz\SyliusCmsPagePlugin\Component\PageFormComponent
        arguments:
            - '@monsieurbiz_cms_page.repository.page'
            - '@form.factory'
            - '%monsieurbiz_cms_page.model.page.class%'
            - 'MonsieurBiz\SyliusCmsPagePlugin\Form\Type\PageType'
        tags:
            - { name: 'sylius.live_component.admin', key: 'sylius_admin:monsieurbiz_cms_page:page:form' }
